### ISSUE TITLE
Multiple tests failing oddly.

### ISSUE THREAD

**Issue by wgaylord** [Deamon5550/Despector#11]
> PS C:\Users\chibi\Downloads\Despector-master> .\gradlew.bat
> Downloading https://services.gradle.org/distributions/gradle-4.1-bin.zip
> ................................................................
> Unzipping C:\Users\chibi\.gradle\wrapper\dists\gradle-4.1-bin\c3kp51zwwt108wc78u68yt7vs\gradle-4.1-bin.zip to C:\Users\chibi\.gradle\wrapper\dists\gradle-4.1-bin\c3kp51zwwt108wc78u68yt7vs
> Starting a Gradle Daemon (subsequent builds will be faster)
> Download https://plugins.gradle.org/m2/com/github/jengelman/gradle/plugins/shadow/2.0.1/shadow-2.0.1.pom
> Download https://plugins.gradle.org/m2/gradle/plugin/net/minecrell/licenser/0.3/licenser-0.3.pom
> Download https://plugins.gradle.org/m2/org/codehaus/groovy/groovy-backports-compat23/2.4.4/groovy-backports-compat23-2.4.4.pom
> Download https://plugins.gradle.org/m2/org/codehaus/groovy/groovy-backports-compat23/2.4.4/groovy-backports-compat23-2.4.4.jar
> Download https://plugins.gradle.org/m2/com/github/jengelman/gradle/plugins/shadow/2.0.1/shadow-2.0.1.jar
> Download https://plugins.gradle.org/m2/gradle/plugin/net/minecrell/licenser/0.3/licenser-0.3.jar
> Download https://repo1.maven.org/maven2/ninja/leaping/configurate/configurate-hocon/3.2/configurate-hocon-3.2.pom
> Download https://repo1.maven.org/maven2/com/google/guava/guava/18.0/guava-18.0.pom
> Download https://repo1.maven.org/maven2/com/google/code/findbugs/jsr305/1.3.9/jsr305-1.3.9.pom
> Download https://repo1.maven.org/maven2/org/ow2/asm/asm-all/5.0.3/asm-all-5.0.3.pom
> Download https://repo1.maven.org/maven2/ninja/leaping/configurate/configurate-parent/3.2/configurate-parent-3.2.pom
> Download https://repo1.maven.org/maven2/com/google/guava/guava-parent/18.0/guava-parent-18.0.pom
> Download https://repo1.maven.org/maven2/org/ow2/asm/asm-parent/5.0.3/asm-parent-5.0.3.pom
> Download https://repo1.maven.org/maven2/com/typesafe/config/1.3.0/config-1.3.0.pom
> Download https://repo1.maven.org/maven2/ninja/leaping/configurate/configurate-core/3.2/configurate-core-3.2.pom
> Download https://repo1.maven.org/maven2/com/typesafe/config/1.3.0/config-1.3.0.jar
> Download https://repo1.maven.org/maven2/ninja/leaping/configurate/configurate-hocon/3.2/configurate-hocon-3.2.jar
> Download https://repo1.maven.org/maven2/ninja/leaping/configurate/configurate-core/3.2/configurate-core-3.2.jar
> Download https://repo1.maven.org/maven2/org/ow2/asm/asm-all/5.0.3/asm-all-5.0.3.jar
> Download https://repo1.maven.org/maven2/com/google/guava/guava/18.0/guava-18.0.jar
> Download https://repo1.maven.org/maven2/com/google/code/findbugs/jsr305/1.3.9/jsr305-1.3.9.jar
> 
> > Task :compileJava
> C:\Users\chibi\Downloads\Despector-master\src\main\java\org\spongepowered\despector\ast\AnnotationType.java:37: warning: [overrides] Class AnnotationType overrides equals, but neither it nor any superclass overrides hashCode method
> public class AnnotationType {
>        ^
> C:\Users\chibi\Downloads\Despector-master\src\main\java\org\spongepowered\despector\ast\Locals.java:302: warning: [overrides] Class LocalInstance overrides equals, but neither it nor any superclass overrides hashCode method
>     public static class LocalInstance {
>                   ^
> C:\Users\chibi\Downloads\Despector-master\src\main\java\org\spongepowered\despector\ast\generic\MethodSignature.java:40: warning: [overrides] Class MethodSignature overrides equals, but neither it nor any superclass overrides hashCode method
> public class MethodSignature {
>        ^
> C:\Users\chibi\Downloads\Despector-master\src\main\java\org\spongepowered\despector\ast\generic\TypeParameter.java:41: warning: [overrides] Class TypeParameter overrides equals, but neither it nor any superclass overrides hashCode method
> public class TypeParameter {
>        ^
> C:\Users\chibi\Downloads\Despector-master\src\main\java\org\spongepowered\despector\ast\generic\GenericClassTypeSignature.java:40: warning: [overrides] Class GenericClassTypeSignature overrides equals, but neither it nor any superclass overrides hashCode method
> public class GenericClassTypeSignature extends TypeSignature {
>        ^
> C:\Users\chibi\Downloads\Despector-master\src\main\java\org\spongepowered\despector\ast\generic\TypeArgument.java:39: warning: [overrides] Class TypeArgument overrides equals, but neither it nor any superclass overrides hashCode method
> public class TypeArgument {
>        ^
> C:\Users\chibi\Downloads\Despector-master\src\main\java\org\spongepowered\despector\ast\generic\ClassTypeSignature.java:40: warning: [overrides] Class ClassTypeSignature overrides equals, but neither it nor any superclass overrides hashCode method
> public class ClassTypeSignature extends TypeSignature {
>        ^
> C:\Users\chibi\Downloads\Despector-master\src\main\java\org\spongepowered\despector\ast\generic\TypeVariableSignature.java:37: warning: [overrides] Class TypeVariableSignature overrides equals, but neither it nor any superclass overrides hashCode method
> public class TypeVariableSignature extends TypeSignature {
>        ^
> C:\Users\chibi\Downloads\Despector-master\src\main\java\org\spongepowered\despector\ast\generic\VoidTypeSignature.java:35: warning: [overrides] Class VoidTypeSignature overrides equals, but neither it nor any superclass overrides hashCode method
> public final class VoidTypeSignature extends TypeSignature {
>              ^
> C:\Users\chibi\Downloads\Despector-master\src\main\java\org\spongepowered\despector\parallel\Scheduler.java:48: warning: [rawtypes] found raw type: Scheduler.Worker
>         this.workers = new Worker[workers];
>                            ^
>   missing type arguments for generic class Scheduler<T>.Worker<R>
>   where R,T are type-variables:
>     R extends Object declared in class Scheduler.Worker
>     T extends Runnable declared in class Scheduler
> 10 warnings
> 
> Download https://repo1.maven.org/maven2/junit/junit/4.11/junit-4.11.pom
> Download https://repo1.maven.org/maven2/org/mockito/mockito-core/1.9.5/mockito-core-1.9.5.pom
> Download https://repo1.maven.org/maven2/org/objenesis/objenesis/1.0/objenesis-1.0.pom
> Download https://repo1.maven.org/maven2/org/mockito/mockito-core/1.9.5/mockito-core-1.9.5.jar
> Download https://repo1.maven.org/maven2/org/objenesis/objenesis/1.0/objenesis-1.0.jar
> Download https://repo1.maven.org/maven2/junit/junit/4.11/junit-4.11.jar
> 
> > Task :test
> 
> org.spongepowered.test.ast.LambdaTest > testMethodRef FAILED
>     org.junit.ComparisonFailure at LambdaTest.java:89
> 
> org.spongepowered.test.decompile.SwitchTests > testReturnSwitchEclipse FAILED
>     org.junit.ComparisonFailure at SwitchTests.java:258
> 
> org.spongepowered.test.kotlin.BasicTests > testNoVoidReturnDeclared FAILED
>     org.junit.ComparisonFailure at BasicTests.java:78
> 
> org.spongepowered.test.kotlin.BasicTests > testLocals FAILED
>     org.junit.ComparisonFailure at BasicTests.java:108
> 
> org.spongepowered.test.kotlin.RangeTests > testIfRange FAILED
>     org.junit.ComparisonFailure at RangeTests.java:84
> 
> org.spongepowered.test.kotlin.StringTests > testSimpleStringTemplate FAILED
>     org.junit.ComparisonFailure at StringTests.java:66
> 
> 122 tests completed, 6 failed
> 
> 
> FAILURE: Build failed with an exception.
> 
> * What went wrong:
> Execution failed for task ':test'.
> > There were failing tests. See the report at: file:///C:/Users/chibi/Downloads/Despector-master/build/reports/tests/test/index.html
> 
> * Try:
> Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
> 
> * Get more help at https://help.gradle.org
> 
> BUILD FAILED in 5m 12s
> 15 actionable tasks: 12 executed, 3 up-to-date

**Comment by mikroskeem** [comment]
Use paste service next time, e.g https://hasteb.in or such

**Comment by Deamon5550** [comment]
Fixed in 370be4ff5f6e0676841f44f64eb75bf81bd1994a 58727cccd23dc415855c1a912d66b6e2b30adcbd
