### ISSUE TITLE
Despector fails to parse signatures with child classes

### ISSUE THREAD

**Issue by mikroskeem** [Deamon5550/Despector#9]
Stack trace:
https://paste.wut.ee/obixajavat.rb

Kotlin class:
https://paste.wut.ee/mokayazonu.cpp

ASMifier dump of target class:
https://paste.wut.ee/oviyoxoyij.java

**Comment by Deamon5550** [comment]
Yes https://github.com/Despector/Despector/blob/master/src/main/java/org/spongepowered/despector/util/SignatureParser.java#L185 :)

**Comment by mikroskeem** [comment]
Oh, haven't peeked into source yet :smile: no wonder
